/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicMotionIndexRouteImport } from './routes/(public)/motion/index'
import { Route as publicLoginIndexRouteImport } from './routes/(public)/login/index'
import { Route as publicAboutIndexRouteImport } from './routes/(public)/about/index'
import { Route as playPlayIndexRouteImport } from './routes/(play)/play/index'
import { Route as playAgainIndexRouteImport } from './routes/(play)/again/index'
import { Route as mainStoriesIndexRouteImport } from './routes/(main)/stories/index'
import { Route as mainSettingsIndexRouteImport } from './routes/(main)/settings/index'
import { Route as mainMyStoriesIndexRouteImport } from './routes/(main)/my-stories/index'
import { Route as mainHomeIndexRouteImport } from './routes/(main)/home/index'
import { Route as mainCreateStoryIndexRouteImport } from './routes/(main)/create-story/index'
import { Route as mainBookmarkIndexRouteImport } from './routes/(main)/bookmark/index'
import { Route as mainAnalyticsIndexRouteImport } from './routes/(main)/analytics/index'
import { Route as mainStoriesIdRouteImport } from './routes/(main)/stories/$id'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicMotionIndexRoute = publicMotionIndexRouteImport.update({
  id: '/(public)/motion/',
  path: '/motion/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginIndexRoute = publicLoginIndexRouteImport.update({
  id: '/(public)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutIndexRoute = publicAboutIndexRouteImport.update({
  id: '/(public)/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const playPlayIndexRoute = playPlayIndexRouteImport.update({
  id: '/(play)/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const playAgainIndexRoute = playAgainIndexRouteImport.update({
  id: '/(play)/again/',
  path: '/again/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainStoriesIndexRoute = mainStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSettingsIndexRoute = mainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainMyStoriesIndexRoute = mainMyStoriesIndexRouteImport.update({
  id: '/my-stories/',
  path: '/my-stories/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainHomeIndexRoute = mainHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainCreateStoryIndexRoute = mainCreateStoryIndexRouteImport.update({
  id: '/create-story/',
  path: '/create-story/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainBookmarkIndexRoute = mainBookmarkIndexRouteImport.update({
  id: '/bookmark/',
  path: '/bookmark/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAnalyticsIndexRoute = mainAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainStoriesIdRoute = mainStoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/stories/$id': typeof mainStoriesIdRoute
  '/analytics': typeof mainAnalyticsIndexRoute
  '/bookmark': typeof mainBookmarkIndexRoute
  '/create-story': typeof mainCreateStoryIndexRoute
  '/home': typeof mainHomeIndexRoute
  '/my-stories': typeof mainMyStoriesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
  '/stories': typeof mainStoriesIndexRoute
  '/again': typeof playAgainIndexRoute
  '/play': typeof playPlayIndexRoute
  '/about': typeof publicAboutIndexRoute
  '/login': typeof publicLoginIndexRoute
  '/motion': typeof publicMotionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/stories/$id': typeof mainStoriesIdRoute
  '/analytics': typeof mainAnalyticsIndexRoute
  '/bookmark': typeof mainBookmarkIndexRoute
  '/create-story': typeof mainCreateStoryIndexRoute
  '/home': typeof mainHomeIndexRoute
  '/my-stories': typeof mainMyStoriesIndexRoute
  '/settings': typeof mainSettingsIndexRoute
  '/stories': typeof mainStoriesIndexRoute
  '/again': typeof playAgainIndexRoute
  '/play': typeof playPlayIndexRoute
  '/about': typeof publicAboutIndexRoute
  '/login': typeof publicLoginIndexRoute
  '/motion': typeof publicMotionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(main)/stories/$id': typeof mainStoriesIdRoute
  '/(main)/analytics/': typeof mainAnalyticsIndexRoute
  '/(main)/bookmark/': typeof mainBookmarkIndexRoute
  '/(main)/create-story/': typeof mainCreateStoryIndexRoute
  '/(main)/home/': typeof mainHomeIndexRoute
  '/(main)/my-stories/': typeof mainMyStoriesIndexRoute
  '/(main)/settings/': typeof mainSettingsIndexRoute
  '/(main)/stories/': typeof mainStoriesIndexRoute
  '/(play)/again/': typeof playAgainIndexRoute
  '/(play)/play/': typeof playPlayIndexRoute
  '/(public)/about/': typeof publicAboutIndexRoute
  '/(public)/login/': typeof publicLoginIndexRoute
  '/(public)/motion/': typeof publicMotionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories/$id'
    | '/analytics'
    | '/bookmark'
    | '/create-story'
    | '/home'
    | '/my-stories'
    | '/settings'
    | '/stories'
    | '/again'
    | '/play'
    | '/about'
    | '/login'
    | '/motion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories/$id'
    | '/analytics'
    | '/bookmark'
    | '/create-story'
    | '/home'
    | '/my-stories'
    | '/settings'
    | '/stories'
    | '/again'
    | '/play'
    | '/about'
    | '/login'
    | '/motion'
  id:
    | '__root__'
    | '/(main)'
    | '/(public)/'
    | '/(main)/stories/$id'
    | '/(main)/analytics/'
    | '/(main)/bookmark/'
    | '/(main)/create-story/'
    | '/(main)/home/'
    | '/(main)/my-stories/'
    | '/(main)/settings/'
    | '/(main)/stories/'
    | '/(play)/again/'
    | '/(play)/play/'
    | '/(public)/about/'
    | '/(public)/login/'
    | '/(public)/motion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
  playAgainIndexRoute: typeof playAgainIndexRoute
  playPlayIndexRoute: typeof playPlayIndexRoute
  publicAboutIndexRoute: typeof publicAboutIndexRoute
  publicLoginIndexRoute: typeof publicLoginIndexRoute
  publicMotionIndexRoute: typeof publicMotionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/motion/': {
      id: '/(public)/motion/'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof publicMotionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login/': {
      id: '/(public)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about/': {
      id: '/(public)/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(play)/play/': {
      id: '/(play)/play/'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof playPlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(play)/again/': {
      id: '/(play)/again/'
      path: '/again'
      fullPath: '/again'
      preLoaderRoute: typeof playAgainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/stories/': {
      id: '/(main)/stories/'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof mainStoriesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/settings/': {
      id: '/(main)/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/my-stories/': {
      id: '/(main)/my-stories/'
      path: '/my-stories'
      fullPath: '/my-stories'
      preLoaderRoute: typeof mainMyStoriesIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/home/': {
      id: '/(main)/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof mainHomeIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/create-story/': {
      id: '/(main)/create-story/'
      path: '/create-story'
      fullPath: '/create-story'
      preLoaderRoute: typeof mainCreateStoryIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/bookmark/': {
      id: '/(main)/bookmark/'
      path: '/bookmark'
      fullPath: '/bookmark'
      preLoaderRoute: typeof mainBookmarkIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/analytics/': {
      id: '/(main)/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof mainAnalyticsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/stories/$id': {
      id: '/(main)/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof mainStoriesIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainStoriesIdRoute: typeof mainStoriesIdRoute
  mainAnalyticsIndexRoute: typeof mainAnalyticsIndexRoute
  mainBookmarkIndexRoute: typeof mainBookmarkIndexRoute
  mainCreateStoryIndexRoute: typeof mainCreateStoryIndexRoute
  mainHomeIndexRoute: typeof mainHomeIndexRoute
  mainMyStoriesIndexRoute: typeof mainMyStoriesIndexRoute
  mainSettingsIndexRoute: typeof mainSettingsIndexRoute
  mainStoriesIndexRoute: typeof mainStoriesIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainStoriesIdRoute: mainStoriesIdRoute,
  mainAnalyticsIndexRoute: mainAnalyticsIndexRoute,
  mainBookmarkIndexRoute: mainBookmarkIndexRoute,
  mainCreateStoryIndexRoute: mainCreateStoryIndexRoute,
  mainHomeIndexRoute: mainHomeIndexRoute,
  mainMyStoriesIndexRoute: mainMyStoriesIndexRoute,
  mainSettingsIndexRoute: mainSettingsIndexRoute,
  mainStoriesIndexRoute: mainStoriesIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
  playAgainIndexRoute: playAgainIndexRoute,
  playPlayIndexRoute: playPlayIndexRoute,
  publicAboutIndexRoute: publicAboutIndexRoute,
  publicLoginIndexRoute: publicLoginIndexRoute,
  publicMotionIndexRoute: publicMotionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
